### ISSUE TITLE
edb-terraform executable installation

### ISSUE THREAD

**Issue by ashersilver** [EnterpriseDB/edb-terraform#63]
Its not clear where the edb-terraform needs to be executed from .

`edb-terraform setup'
Traceback (most recent call last):

File "/usr/local/lib/python3.11/site-packages/edbterraform/CLI.py", line 27, in execute_shell  
process = subprocess.check_output(  
^^^^^^^^^^^^^^^^^^^^^^^^

File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output  
return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,  
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/usr/local/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run  
raise CalledProcessError(retcode, process.args,

subprocess.CalledProcessError: Command '/bin/bash /var/folders/tm/4r9wl7rn5y5gg2rln8q85xx00000gn/T/tmpnvk40x2g.sh' returned non-zero exit status 134.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "/usr/local/bin/edb-terraform", line 8, in sys.exit(entry_point()) ^^^^^^^^^^^^^

File "/usr/local/lib/python3.11/site-packages/edbterraform/**main**.py", line 24, in entry_point  
main()

File "/usr/local/lib/python3.11/site-packages/edbterraform/**main**.py", line 17, in main  
outputs = arg_parser.process_args()  
^^^^^^^^^^^^^^^^^^^^^^^^^

File "/usr/local/lib/python3.11/site-packages/edbterraform/args.py", line 259, in process_args  
terraform.install()

File "/usr/local/lib/python3.11/site-packages/edbterraform/CLI.py", line 275, in install  
execute_temporary_script(script_name)

File "/usr/local/lib/python3.11/site-packages/edbterraform/CLI.py", line 91, in execute_temporary_script  
output = execute_shell(['/bin/bash', script_name])  
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/usr/local/lib/python3.11/site-packages/edbterraform/CLI.py", line 40, in execute_shell  
raise Exception(

Exception: executable seems to be missing. Please install it or check your PATH variable

	Its not clear where the executable will be installed .. clearly there are files inside the 

	/usr/local/bin      folder and not in the  `~/.edb-terraform/bin folder.`

**Comment by bryan-bar** [comment]
@ashersilver
What system is this on?
You can skip this command and use `edb-terraform generate` directly to only generate the files. If you use the `--validate` option then it will look inside of `~/.edb-terraform/bin` and then your PATH and run `terraform init`, `terraform plan` and a targeted `terraform apply`.

The setup command tries to install `terraform` inside of `~/.edb-terraform/bin` by default. You can specify the install directory with `--bin_path` or use the environment variable `ET_BIN_PATH`.

**Comment by shaktishikha** [comment]
@ashersilver are there any updates on it? Can we close this issue?
